version: 0.0.{build}
skip_tags: true
branches:
  only:
    - mainline
    - development
    - /release\/.+/
image:
- Visual Studio 2019
environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  access_token:
    secure: bgpjXvIfg4d/v1n+ngNN6ssEXpd2CV/viaR/i5fZiiMuYq8rZqumWCvvu9U9BdOV
  APPVEYOR_API_KEY:
    secure: rpXPHQWPOYenbPde1TBHi1GCd4ZQmZdvHvgDHAD63ls=
  APPVEYOR_NUGET_SOURCE:
    secure: VuWtCLy/4eydK+DVx9MO6TQr3YkXxpSrdWPKsCdIeTJwX5TwLG1AdFFvku5e/3BkvuLXWaWavRnZm57HBrG4oZSvKfpS5UzlrlxMRpvnicY=
  PRIVATE_FEED_USERNAME:
    secure: fPwiWP/d3K8GFL6pwRydkUZiILhT8xvgQPlJsLa0Mvw=
  PRIVATE_FEED_PASSWORD:
    secure: XcY76bgmAreXfL3BlYc4FouQYEFIx2NkizyyILCiUlo=
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml # Choco executables
  - C:\ProgramData\chocolatey\lib -> appveyor.yml # Choco packages
  - '%USERPROFILE%\.nuget\packages -> **.sln, **.csproj' # NuGet packages
configuration: Release
platform: Any CPU
install:
- choco install gitversion.portable -pre -y
build:
  verbosity: minimal
before_build:
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
build_script:
- ps: .\build.ps1 --target=Windows
test: off
on_success:
- ps: if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) { .\tag.ps1 }
notifications:
- provider: Slack
  incoming_webhook:
    secure: htrSyOk4MXa2SEcv3h7adfJ4y1lNavFox9GFZt8Y+JbrlFkOd6CvcXwu9mAsCQcLpgaHT8SrBqUS+2rEFfpLv1g6i+RxyDOZijq4aTaD5fU=
  channel: app-veyor
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true