version: 0.0.{build}
skip_tags: true
branches:
  only:
    - mainline
    - development
    - /release\/.+/
image:
- Visual Studio 2019
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  access_token:
    secure: bgpjXvIfg4d/v1n+ngNN6ssEXpd2CV/viaR/i5fZiiMuYq8rZqumWCvvu9U9BdOV
configuration: Release
platform: Any CPU
install:
- choco install gitversion.portable -pre -y
build:
  verbosity: minimal
before_build:
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
build_script:
- ps: .\build.ps1 --target=Windows
test: off
notifications:
- provider: Slack
  incoming_webhook:
    secure: htrSyOk4MXa2SEcv3h7adfJ4y1lNavFox9GFZt8Y+JbrlFkOd6CvcXwu9mAsCQcLpgaHT8SrBqUS+2rEFfpLv1g6i+RxyDOZijq4aTaD5fU=
  channel: app-veyor
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true