variables:
  buildConfiguration: 'Release'
  vstsFeed: 'cb5e5c0b-aa1d-4688-a3ff-e65476c9e30a/d99cfdbb-c33d-4667-9065-a67e001d5e66'

trigger:
- development
- release/mainline
- release/*

pr:
- development
- release/mainline

stages:
- stage: build_stage
  displayName: Initialization
  jobs:
    - job: build
      displayName: Build

      pool:
        vmImage: ubuntu-latest

      steps:
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: '5.6.8'

      - task: gitversion/execute@0
        displayName: Execute GitVersion
        inputs:
          updateAssemblyInfo: true

      - task: DotNetCoreCLI@2
        displayName: Build Package
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration) /p:PackageVersion=$(Build.BuildNumber)'

      - task: DotNetCoreCLI@2
        displayName: Unit Tests
        inputs:
          command: 'test'
          publishTestResults: true

      - task: DotNetCoreCLI@2
        condition: eq(variables['Build.Reason'], 'PullRequest')
        displayName: Push Package
        inputs:
          command: 'push'
          packagesToPush: './Illusion.Common.*/bin/Release/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: $(vstsFeed)
