variables:
  buildConfiguration: 'Release'
  vstsFeed: 'cb5e5c0b-aa1d-4688-a3ff-e65476c9e30a/d99cfdbb-c33d-4667-9065-a67e001d5e66'

trigger:
- mainline
- development
- release/*

pr:
- mainline
- development

stages:
- stage: initialization_stage
  displayName: Initialization
  jobs:
  - template: pipeline/init.job.template.yml

- stage: build_stage
  displayName: Build
  jobs:
  - template: pipeline/build.job.template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      vstsFeed: $(vstsFeed)
