
parameters:
    name: '--'
    codeName: '--'
    BuildConfiguration: 'Release'
    BuildPlatform: 'any cpu'
    projectName: '--'
    RestoreBuildProjects: '$(project.file)'
    vstsFeed: '--'

jobs:
- job: ${{ parameters.name }}
  dependsOn: Build_Queue
  continueOnError: true
  variables:
    BuildConfiguration: ${{ parameters.BuildConfiguration }}
    BuildPlatform: ${{ parameters.BuildPlatform }}
    project.path: $(Build.SourcesDirectory)/${{ parameters.projectName }}
    project.file: ${{ parameters.projectName }}/${{ parameters.projectName }}.csproj
    Parameters.RestoreBuildProjects: ${{ parameters.RestoreBuildProjects }}
    myBuildQueue: $[ dependencies.Build_Queue.outputs['setBuildQueue.buildQueue'] ]
    version: $[ dependencies.Build_Queue.outputs['SetVersion.version'] ]
  condition: and(succeeded(), or(contains(dependencies.Build_Queue.outputs['setBuildQueue.buildQueue'], '${{ parameters.codeName }}'), contains(dependencies.Build_Queue.outputs['setBuildQueue.buildQueue'], 'all'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') ))
  steps:
  - task: powershell@2
    displayName: Print Variables
    inputs:
      targetType: inline
      script: |
        'Write-Host "Build Queue init: $(buildQueueInit) and from parameters $(myBuildQueue)"'
        'Write-Host "Current path: $(project.path)"'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      workingDirectory: $(project.path)
      arguments: '--configuration $(BuildConfiguration) /p:PackageVersion=$(version)'

  - task: DotNetCoreCLI@2
    displayName: Unit Tests
    inputs:
      command: 'test'
      workingDirectory: $(project.path)
      publishTestResults: true

  - task: DotNetCoreCLI@2
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: Push Package
    inputs:
      command: 'push'
      packagesToPush: '$(project.path)/bin/Release/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: ${{ parameters.vstsFeed }}