jobs:
  - job: git_version
    displayName: GitVersion

    pool:
      vmImage: ubuntu-latest

    steps:
    - task: gitversion/setup@0
      displayName: Install GitVersion
      inputs:
        versionSpec: '5.6.8'

    - task: gitversion/execute@0
      displayName: Execute GitVersion
      inputs:
        updateAssemblyInfo: true

    - task: Bash@3
      displayName: Environment Variables
      inputs:
        targetType: 'inline'
        script: 'env | sort'
